package practise.models;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * An entity User composed by three fields (id, email, name).
 * The Entity annotation indicates that this class is a JPA entity.
 * The Table annotation specifies the name for the table in the db.
 *
 * @author practise
 */
@Entity
@Table(name = "users")
public class User {

  // ==============
  // PRIVATE FIELDS
  // ==============
  
  // An autogenerated id (unique for each user in the db)
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private long id;
  
  // The user email
  @NotNull
  private String project;
  
  // The user name
  @NotNull
  private String name;
  
  @NotNull
  private String designation;

  // ==============
  // PUBLIC METHODS
  // ==============
  
  public User() { }

  public User(long id) { 
    this.id = id;
  }
  
  public User(String name, String project, String designation ) {  
    this.name = name;
    this.project = project;
    this.designation = designation;
  }

public long getId() {
	return id;
}

public void setId(long id) {
	this.id = id;
}

public String getProject() {
	return project;
}

public void setProject(String project) {
	this.project = project;
}

public String getName() {
	return name;
}

public void setName(String name) {
	this.name = name;
}

public String getDesignation() {
	return designation;
}

public void setDesignation(String designation) {
	this.designation = designation;
}

  
  
} // class User
